version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234



  goapp:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: 1234